
/// @function summonObject(obj, arguments, _x, _y, _depth)
/// @description Creates an instance of `obj` at (_x, _y) with a depth of `_depth`, and assigns arguments from the `arguments` array
/// @param {object} obj The object to create
/// @param {array} arguments An array of sub-arrays, where each sub-array contains [argument_name, argument_value]
/// Generated by Deepseek and edited by yours truly

function summonObject(obj, arguments = noone){
	var struct = 1;
	if (arguments != noone){
	    // Create a ds_map to hold the arguments
	    var argumentMap = ds_map_create();

	    // Loop through the arguments array
	    for (var i = 0; i < array_length(arguments); i++) {
	        // Get the current sub-array (which contains [argument_name, argument_value])
	        var arg = arguments[i];

	        // Ensure the sub-array has exactly 2 elements (name and value)
	        if (array_length(arg) == 2) {
	            var argName = arg[0]; // Name of the argument (can be a string)
	            var argValue = arg[1]; // Value of the argument

	            // Add the argument to the ds_map
	            argumentMap[? argName] = argValue;
	        } else {
	            show_debug_message("Invalid argument at index " + string(i) + ": Expected [name, value].");
	        }
	    }
		//convert to struct
		struct = ds_map_to_struct(argumentMap)
		ds_map_destroy(argumentMap);
	    // Create the instance with the argument map
	}else{
		struct = {}
	}
	try{
		return instance_create_depth(x, y, 0, obj, struct);
	}catch(e){
		return instance_create_depth(0, 0, 0, obj, struct);
	}
    
}

function getMovementVector(angle){
	return [cos(degtorad(angle)), -sin(degtorad(angle))]
}


/// @function ds_map_to_struct(dsMap)
/// @description Converts a ds_map to a struct.
/// @param {ds_map} dsMap The ds_map to convert.
/// @return {struct} The resulting struct.
/// Generated by Deepseek
function ds_map_to_struct(dsMap) {
    // Create an empty struct
    var resultStruct = {};

    // Get the list of keys from the ds_map
    var keys = ds_map_keys_to_array(dsMap);

    // Loop through the keys and copy them to the struct
    for (var i = 0; i < array_length(keys); i++) {
        var key = keys[i];
        var value = dsMap[? key];

        // Add the key-value pair to the struct
        resultStruct[$ key] = value;
    }

    return resultStruct;
}

//this is way better
function print(){
	if !global.disablePrints{
		var text = ""
		for (var i = 0; i < argument_count; i++){
			text += string(argument[i])
		}
		show_debug_message(text);
	}
}


/// @function stepCollisionWhileWithFailCon(objectArray, step, horizontal)
/// @description Used before colliding with something collideable, will check all object types in objectArray
/// @param {array} objectArray Array of all objects that need to be checked
/// @param {real} step Negative or positive direction
/// @param {real} horizontal y-axis or x-axis? 1 for x-axis, 0 for y-axis

function stepCollisionWhileWithFailCon(objectArray, step, horizontal){
	global.preWhileCoord = [x,y];
	while(!collisionWithArray(objectArray,step,horizontal)){
		x += step*horizontal;
		y += step*!horizontal
		global.whileFail++
		if (global.whileFail == global.whileFailLimit){
			x = global.preWhileCoord[0]
			y = global.preWhileCoord[1]
			global.whileFail = 0
			break;
		}
	}
}

/// @function collisionWithArray(array, step, horizontal)
/// @description Helper function for stepCollisionWhileWithFailCon
/// @param {array} objectArray Array of all objects that need to be checked
/// @param {real} step Negative or positive direction
/// @param {real} horizontal y-axis or x-axis? 1 for x-axis, 0 for y-axis
/// @returns {bool} true if collision with any obj in array, else false
function collisionWithArray(array,step,horizontal){
	var boolean = false;
	for (var i = 0; i < array_length(array); i++) {
		if place_meeting(x+step*horizontal,y+step*!horizontal,array[i]){
			return true
		}
	}
	return false;
}


function is_in_range(value, minimum, maximum) {
    return value > minimum && value < maximum;
}

function normalizedVector(coordsA, coordsB){
	// Get direction vector
	var dir_x = coordsB[0] - coordsA[0];
	var dir_y = coordsB[1] - coordsA[1];

	// Normalize using point_distance (more efficient than manual calculation)
	var dist = point_distance(0, 0, dir_x, dir_y);
	if (dist > 0) {
	    dir_x /= dist;
	    dir_y /= dist;
	}
	return [dir_x, dir_y];
}




/// @function minIndex(...)
/// @description Returns the minimum value and its position among the arguments
/// @param {variadic} values Any number of values to compare
/// @returns {array} [min_value, position_index]
/// made by deepseek, glory to the ccp, i am a lazy BUM!!!!!

function minIndex() {
    if (argument_count == 0) {
        // Handle case with no arguments
        return [undefined, 0];
    }
    
    var min_val = 99999999
    var min_index = 1;
    
    for (var i = 0; i < argument_count; i++) {
        if (argument[i] < min_val) {
            min_val = argument[i];
            min_index = i; 
        }
    }
    
    return [min_val, min_index];
}

/// @function spiralGridScan(centerX, centerY, gridWidth, gridHeight, processCellFunc)
/// @desc Spiral outward from center coordinates (0-based indices)
/// @param {real} _centerX       Grid X center position (0-based)
/// @param {real} _centerY       Grid Y center position (0-based)
/// @param {real} gridWidth      Total width of grid
/// @param {real} gridHeight     Total height of grid
/// @param {function} processCellFunc   Callback for each cell (receives _x,_y)

function spiralGridScan(_centerX, _centerY, gridWidth, gridHeight, processCellFunc) {
    // Directions: right, down, left, up
    var _dirs = [
        {dx:1, dy:0},  
        {dx:0, dy:1},   
        {dx:-1, dy:0},  
        {dx:0, dy:-1}   
    ];
    
    var _currentDir = 0;
    var _stepSize = 1;
    var _stepsTaken = 0;
    var _currentX = _centerX;
    var _currentY = _centerY;
    var _stepChange = 0;
    var _maxRadius = max(
        max(_centerX, gridWidth - _centerX - 1),
        max(_centerY, gridHeight - _centerY - 1)
    );

    // Process center cell first
    if (_currentX >= 0 && _currentX < gridWidth && _currentY >= 0 && _currentY < gridHeight) {
        method_call(processCellFunc, [_currentX, _currentY]);
    }

    // Spiral outward
    while (_stepSize <= _maxRadius * 2) {
        // Move in current direction
        _currentX += _dirs[_currentDir].dx;
        _currentY += _dirs[_currentDir].dy;
        // Process cell if within bounds
        if (_currentX >= 0 && _currentX < gridWidth && _currentY >= 0 && _currentY < gridHeight) {
            method_call(processCellFunc, [_currentX, _currentY]);
        }
        
        _stepsTaken++;
        
        // Change direction when stepSize reached
        if (_stepsTaken >= _stepSize) {
            _stepsTaken = 0;
            _currentDir = (_currentDir + 1) % 4;
            _stepChange++;
            
            // Increase stepSize every 2 direction changes
            if (_stepChange % 2 == 0) {
                _stepSize++;
            }
        }
    }
}


/// @function inRange(value, min, max)
/// @description Returns whether value is between min and max (inclusive)
/// @param {real} value The value to check
/// @param {real} min   Minimum bound
/// @param {real} max   Maximum bound
function inRange(_value, _min, _max) {
    return (_value >= _min && _value <= _max);
}



/// @func   collision_normal(x, y, obj, radius, spacing)
///
/// @desc   Returns a 2D "surface normal" at a point on or near an
///         instance within a test area. The test area is circular
///         and the detected normal direction is returned in degrees.
///         If no collision is found, (-1) is returned. Uses about
///         pi*(radius*radius)/(spacing*spacing) collision checks.
///
/// @param  {real}      x           x-coordinate of point near an instance
/// @param  {real}      y           y-coordinate of point near an instance
/// @param  {object}    obj         object or instance (or all)
/// @param  {real}      radius      radius of test area (default 4)
/// @param  {real}      spacing     space between each sample (default 1)
///
/// @return {real}      direction pointing away from the detected surface
///
/// GMLscripts.com/license

function collision_normal(x, y, obj, radius=4, spacing=1)
{
    var nx = 0;
    var ny = 0;
    if (collision_circle(x, y, radius, obj, true, true) != noone) {
        for (var j=spacing; j<=radius; j+=spacing) {
            for (var i=0; i<radius; i+=spacing) {
                if (point_distance(0, 0, i, j) <= radius) {
                    if (collision_point(x+i, y+j, obj, true, true) == noone) { nx += i; ny += j; }
                    if (collision_point(x+j, y-i, obj, true, true) == noone) { nx += j; ny -= i; }
                    if (collision_point(x-i, y-j, obj, true, true) == noone) { nx -= i; ny -= j; }
                    if (collision_point(x-j, y+i, obj, true, true) == noone) { nx -= j; ny += i; }
                }
            }
        }
        if (nx == 0 && ny == 0) return (-1);
        return point_direction(0, 0, nx, ny);
    }
    return (-1);
}


/// @func   dec_to_hex(dec, len)
///
/// @desc   Returns a given value as a string of hexadecimal digits.
///         Hexadecimal strings can be padded to a minimum length.
///         Note: If the given value is negative, it will
///         be converted using its two's complement form.
///
/// @param  {real}      dec         integer
/// @param  {real}      [len=1]     minimum number of digits
///
/// @return {string}    hexadecimal digits
///
/// GMLscripts.com/license
 
function dec_to_hex(dec, len = 1)
{
    var hex = "";
 
    if (dec < 0) {
        len = max(len, ceil(logn(16, 2 * abs(dec))));
    }
 
    var dig = "0123456789ABCDEF";
    while (len-- || dec) {
        hex = string_char_at(dig, (dec & $F) + 1) + hex;
        dec = dec >> 4;
    }
 
    return hex;
}



function collision_line_point(x1, y1, x2, y2, obj, prec, notme) {
    var rr = collision_line(x1, y1, x2, y2, obj, prec, notme);
    var rx = x2;
    var ry = y2;
    if (rr != noone) {
        var p0 = 0;
        var p1 = 1;
        repeat (ceil(log2(point_distance(x1, y1, x2, y2))) + 1) {
            var np = p0 + (p1 - p0) * 0.5;
            var nx = x1 + (x2 - x1) * np;
            var ny = y1 + (y2 - y1) * np;
            var px = x1 + (x2 - x1) * p0;
            var py = y1 + (y2 - y1) * p0;
            var nr = collision_line(px, py, nx, ny, obj, prec, notme);
            if (nr != noone) {
                rr = nr;
                rx = nx;
                ry = ny;
                p1 = np;
            } else p0 = np;
        }
    }
    return {instance: rr, hitPoint: [rx, ry]};
}

/// point_to_segment_distance(segmentPoint1, segmentPoint2, point, obstacleObj, precise, notme)
/// Distance from point (px,py) to the segment between (x1,y1) and (x2,y2).
/// If the line between the point and the closest point on the segment collides with obstacleObj,
/// the function returns 999999.
function point_to_segment_distance(segmentPoint1, segmentPoint2, point, obstacleObj = obj_solid) {

    var ax = segmentPoint1[0];
    var ay = segmentPoint1[1];
    var bx = segmentPoint2[0];
    var by = segmentPoint2[1];
    var px = point[0];
    var py = point[1];

    var vx = bx - ax;
    var vy = by - ay;
    var wx = px - ax;
    var wy = py - ay;

    var denom = vx*vx + vy*vy;
    var cx, cy; // closest point on segment

    if (denom == 0) {
        // segment is a point -> closest point is A
        cx = ax;
        cy = ay;
    } else {
        // projection factor t = dot(AP,AB) / dot(AB,AB)
        var t = (wx*vx + wy*vy) / denom;

        if (t <= 0) {
            // closest to A
            cx = ax;
            cy = ay;
        } else if (t >= 1) {
            // closest to B
            cx = bx;
            cy = by;
        } else {
            // projection falls within segment, compute projection point
            cx = ax + t * vx;
            cy = ay + t * vy;
        }
    }

    // Check collision between the original point and the closest point on the segment.
    // If any instance of obstacleObj is hit, return the sentinel value.
    if (collision_line(px, py, cx, cy, obstacleObj, false, false) != noone) {
        return distanceNotFound;
    }

    // Otherwise return the true shortest distance
    return point_distance(px, py, cx, cy);
}